package org.saiku;

import net.ttddyy.dsproxy.transform.QueryTransformer;
import net.ttddyy.dsproxy.transform.TransformInfo;

/**
 * This is a very specific query transformer that applies hint to tell derby to disable join order optimizations
 * because some queries we are running have too many joins and as a consequence optimization takes too long to
 * complete.
 *
 * This hint should affect only queries generated by mondrian that are used to calculate grand totals.
 *
 * @author Octavian Ciubotaru
 */
public class DerbyOptimizerHintQueryTransformer implements QueryTransformer {

    private static final String OLD_PREFIX = "select count(*) from (";
    private static final String NEW_PREFIX = "select count(*) from -- DERBY-PROPERTIES joinOrder = FIXED\n(";

    @Override
    public String transformQuery(TransformInfo transformInfo) {
        String query = transformInfo.getQuery();
        if (query.startsWith(OLD_PREFIX)) {
            query = NEW_PREFIX + query.substring(OLD_PREFIX.length());
        }
        return query;
    }
}
